/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface _Master_ {
  NftOutputExtension: NftOutputExtension;
  VerificationOutput: VerificationOutput;
}
export interface NftOutputExtension {
  tape_hash: string;
  cid: string;
}
export interface VerificationOutput {
  version: string;
  cartridge_id: string;
  cartridge_input_index: number;
  cartridge_user_address: string;
  timestamp: number;
  score: number;
  rule_id: string;
  rule_input_index: number;
  tape_hash: string;
  tape_input_index: number;
  user_address: string;
  error_code: number;
  nft_output: string;
}
