services:
    validator:
        image: cartesi/rollups-node:1.4.0
        expose:
            - "10000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:10000/healthz"]
            interval: 10s
            timeout: 1s
            retries: 5
        command:
            # - printenv
            - /bin/bash
            - -c
            - |
                mkdir -p "$CARTESI_SNAPSHOT_DIR"
                cp --recursive /tmp/snapshot/* "$CARTESI_SNAPSHOT_DIR"
                exec cartesi-rollups-node

        env_file:
            - ${CARTESI_BIN_PATH}/node/default.env
        extra_hosts:
            - "host.docker.internal:host-gateway"

    proxy:
        depends_on:
            validator:
                condition: service_healthy

    traefik-config-generator:
        environment:
            TRAEFIK_CONFIG_INSPECT_SERVER: |
                http:
                    routers:
                        inspect_server:
                            rule: "PathPrefix(`/inspect`)"
                            service: inspect_server
                    services:
                        inspect_server:
                            loadBalancer:
                                servers:
                                    - url: "http://validator:10000/inspect"
            TRAEFIK_CONFIG_GRAPHQL_SERVER: |
                http:
                    routers:
                        graphql_server:
                            rule: "PathPrefix(`/graphql`)"
                            service: graphql_server
                    services:
                        graphql_server:
                            loadBalancer:
                                servers:
                                    - url: "http://validator:10000/graphql"
volumes:
    blockchain-data: {}