/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface _Master_ {
  CartridgePayload: CartridgePayload;
  VerifyPayloadProxy: VerifyPayloadProxy;
  RulesOutput: RulesOutput;
  InsertCartridgePayloadProxy: InsertCartridgePayloadProxy;
  RuleCreated: RuleCreated;
  RemoveCartridgePayloadProxy: RemoveCartridgePayloadProxy;
  CartridgeInfo: CartridgeInfo;
  CartridgesOutput: CartridgesOutput;
  RuleDataProxy: RuleDataProxy;
  TransferCartridgePayloadProxy: TransferCartridgePayloadProxy;
  GetRulesPayload: GetRulesPayload;
  VerificationOutput: VerificationOutput;
  CartridgeRemoved: CartridgeRemoved;
  CartridgeInserted: CartridgeInserted;
  RuleTagsOutput: RuleTagsOutput;
}
export interface CartridgePayload {
  id: string;
}
export interface VerifyPayloadProxy {
  rule_id: string;
  outcard_hash: string;
  tape: string;
  claimed_score: number;
}
export interface RulesOutput {
  data: RuleInfo[];
  total: number;
  page: number;
}
export interface RuleInfo {
  id: string;
  name: string;
  description: string;
  cartridge_id: string;
  created_by: string;
  created_at: number;
  args: string;
  in_card: string;
  score_function: string;
  n_tapes: number;
  n_verified: number;
  start?: number;
  end?: number;
  tags: string[];
}
export interface InsertCartridgePayloadProxy {
  data: string;
}
export interface RuleCreated {
  rule_id: string;
  created_by: string;
  created_at: number;
}
export interface RemoveCartridgePayloadProxy {
  id: string;
}
export interface CartridgeInfo {
  id: string;
  name: string;
  user_address: string;
  authors: string[];
  info?: InfoCartridge;
  created_at: number;
  cover?: string;
}
export interface InfoCartridge {
  name: string;
  summary?: string;
  description?: string;
  version?: string;
  status?: string;
  tags: string[];
  authors?: Author[];
  url?: string;
}
export interface Author {
  name: string;
  link: string;
}
export interface CartridgesOutput {
  data: CartridgeInfo[];
  total: number;
  page: number;
}
export interface RuleDataProxy {
  cartridge_id: string;
  name: string;
  description: string;
  args: string;
  in_card: string;
  score_function: string;
  start: number;
  end: number;
  tags: string[];
}
export interface TransferCartridgePayloadProxy {
  id: string;
  new_user_address: string;
}
export interface GetRulesPayload {
  cartridge_id?: string;
  id?: string;
  ids?: string[];
  active_ts?: number;
  name?: string;
  page?: number;
  page_size?: number;
}
export interface VerificationOutput {
  version: string;
  cartridge_id: string;
  cartridge_input_index: number;
  cartridge_user_address: string;
  timestamp: number;
  score: number;
  rule_id: string;
  rule_input_index: number;
  tape_hash: string;
  tape_input_index: number;
  user_address: string;
  error_code: number;
  reserved: string;
}
export interface CartridgeRemoved {
  cartridge_id: string;
  timestamp: number;
}
export interface CartridgeInserted {
  cartridge_id: string;
  user_address: string;
  timestamp: number;
}
export interface RuleTagsOutput {
  tags: string[];
}
