// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ResourceId } from "@latticexyz/world/src/WorldResourceId.sol";
import { Proof } from "@cartesi/rollups/contracts/dapp/ICartesiDApp.sol";

/**
 * @title IDappSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDappSystem {
  error DappSystem__InvalidOwner();
  error DappSystem__InvalidResource();
  error DappSystem__ArrayError();
  error DappSystem__InvalidPayload();

  function core__addInput(address _dapp, bytes calldata _payload) external returns (bytes32);

  function core__addInputToCartesiInputBox(bytes32 resourceId, bytes calldata _payload) external returns (bytes32);

  function core__setNamespaceSystem(address _dapp, ResourceId systemResource) external;

  function core__addSystemSubscription(ResourceId systemResource, ResourceId systemToSubscribe) external;

  function core__removeSystemSubscription(ResourceId systemResource, ResourceId systemToSubscribe) external;

  function core__validateNotice(
    ResourceId system,
    bytes calldata _payload,
    uint32[] calldata _payloadSliceIndex,
    Proof[] calldata _proofs
  ) external view returns (bool);
}
