// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { DappMessagesDebug, DappMessagesDebugData } from "./tables/DappMessagesDebug.sol";
import { DebugCounter } from "./tables/DebugCounter.sol";
